#ifndef __AG_EXPORT__
#define __AG_EXPORT__

#include <agexport.h>
#include <ag3d.h>

#ifdef __cplusplus
extern "C" {
#endif

/***************************************************************/
/*                       FrameBuffer                           */
/***************************************************************/
#define AGE_FB_WIDTH	(1024)
#define AGE_FB_HEIGHT	(768)
#define AGE_DISP_WIDTH	(1024)
#define AGE_DISP_HEIGHT	(768)
#define AGE_FB_ADDR0	(7602176)
#define AGE_FB_ADDR1	(6815744)
#define AGE_ZB_ADDR	(6815744)
#define AGE_ZB_DEPTH	(4)
#define AGE_ZMD	(1)
#define AGE_AAC_ADDR	(13631488)
#define AGE_AAC_SIZE	(13631488)
#define AGE_SOUND_ROM_OFFSET	(0x80000)

/***************************************************************/
/*                    Rom Member Symbol                        */
/***************************************************************/
#define AG_CG_INFO_FOOD	(0)
#define AG_CG_INFO_TIME	(1)
#define AG_CG_WORKSTAND	(2)
#define AG_CG_GAMECLEAR	(3)
#define AG_CG_GAMEOVER	(4)
#define AG_CG_GAMESTART	(5)
#define AG_CG_SCOREFONT	(6)
#define AG_CG_TITLE	(7)
#define AG_CG_EFFECT_DMG1	(8)
#define AG_CG_EFFECT_DMG2	(9)
#define AG_CG_EFFECT_RECOVERY1	(10)
#define AG_CG_EFFECT_RECOVERY2	(11)
#define AG_CG_EFFECT_RECOVERY3	(12)
#define AG_CG_ENEMY_FROGA1	(13)
#define AG_CG_ENEMY_FROGA2	(14)
#define AG_CG_ENEMY_FROGA3	(15)
#define AG_CG_ICON_LIFE1	(16)
#define AG_CG_ICON_LIFE2	(17)
#define AG_CG_ICON_LIFE3	(18)
#define AG_CG_ENEMY_IGAGURI	(19)
#define AG_CG_OBJ_BLOCK1	(20)
#define AG_CG_OBJ_BLOCK2	(21)
#define AG_CG_OBJ_BLOCK3	(22)
#define AG_CG_OBJ_BLOCK4	(23)
#define AG_CG_OBJ_BOX1	(24)
#define AG_CG_OBJ_BOX2	(25)
#define AG_CG_OBJ_CANNONBALL	(26)
#define AG_CG_OBJ_CROW_BODY1	(27)
#define AG_CG_OBJ_CROW_BODY2	(28)
#define AG_CG_OBJ_CROW_BODY3	(29)
#define AG_CG_OBJ_CROW_WING_L1	(30)
#define AG_CG_OBJ_CROW_WING_L2	(31)
#define AG_CG_OBJ_CROW_WING_L3	(32)
#define AG_CG_OBJ_CROW_WING_R1	(33)
#define AG_CG_OBJ_CROW_WING_R2	(34)
#define AG_CG_OBJ_CROW_WING_R3	(35)
#define AG_CG_OBJ_GRASS	(36)
#define AG_CG_OBJ_JUMP1	(37)
#define AG_CG_OBJ_JUMP2	(38)
#define AG_CG_OBJ_JUMP3	(39)
#define AG_CG_OBJ_KEY	(40)
#define AG_CG_OBJ_KEYHOLE	(41)
#define AG_CG_OBJ_MORTAR1	(42)
#define AG_CG_OBJ_MORTAR2	(43)
#define AG_CG_OBJ_NEEDLE	(44)
#define AG_CG_OBJ_PULLEY1	(45)
#define AG_CG_OBJ_PULLEY2	(46)
#define AG_CG_OBJ_PULLEY3	(47)
#define AG_CG_OBJ_PULLEY4	(48)
#define AG_CG_OBJ_PULLEY5	(49)
#define AG_CG_OBJ_SLOPE_0GRASS1	(50)
#define AG_CG_OBJ_SLOPE_0GRASS2	(51)
#define AG_CG_OBJ_SLOPE_0GRASS3	(52)
#define AG_CG_OBJ_SLOPE_0GRASS4	(53)
#define AG_CG_OBJ_SLOPE_0GRASS5	(54)
#define AG_CG_OBJ_SLOPE_30GRASS1	(55)
#define AG_CG_OBJ_SLOPE_30GRASS2	(56)
#define AG_CG_OBJ_SLOPE_30GRASS3	(57)
#define AG_CG_OBJ_SLOPE_30GRASS4	(58)
#define AG_CG_OBJ_SLOPE_30GRASS5	(59)
#define AG_CG_OBJ_SLOPE_30GRASS6	(60)
#define AG_CG_OBJ_SLOPE_30GRASS7	(61)
#define AG_CG_OBJ_SLOPE_30GRASS8	(62)
#define AG_CG_OBJ_SLOPE_45GRASS1	(63)
#define AG_CG_OBJ_SLOPE_45GRASS2	(64)
#define AG_CG_OBJ_SLOPE_45GRASS3	(65)
#define AG_CG_OBJ_SLOPE_45GRASS4	(66)
#define AG_CG_OBJ_SLOPE_45GRASS5	(67)
#define AG_CG_OBJ_SLOPE_45GRASS6	(68)
#define AG_CG_OBJ_SLOPE_GROUND1	(69)
#define AG_CG_OBJ_SLOPE_GROUND2	(70)
#define AG_CG_OBJ_SLOPE_GROUND3	(71)
#define AG_CG_OBJ_SNAKE1	(72)
#define AG_CG_OBJ_SNAKE2	(73)
#define AG_CG_OBJ_SNAKE3	(74)
#define AG_CG_OBJ_SNAKE4	(75)
#define AG_CG_OBJ_SWITCH1	(76)
#define AG_CG_OBJ_SWITCH2	(77)
#define AG_CG_OBJ_TAKE1	(78)
#define AG_CG_OBJ_TAKE2	(79)
#define AG_CG_OBJ_TAKE3	(80)
#define AG_CG_OBJ_TAKE4	(81)
#define AG_CG_OBJ_TAKE5	(82)
#define AG_CG_OBJ_WHEEL	(83)
#define AG_CG_OBJ_WORKSTAND1	(84)
#define AG_CG_OBJ_WORKSTAND2	(85)
#define AG_CG_OBJ_WORKSTAND3	(86)
#define AG_CG_OBJ_WORKSTAND4	(87)
#define AG_CG_UI_ITEMFLAME	(88)
#define AG_CG_BG_0_0	(89)
#define AG_CG_BG_0_1	(90)
#define AG_CG_BG_0_2	(91)
#define AG_CG_BG_0_3	(92)
#define AG_CG_BG_0_4	(93)
#define AG_CG_BG_1_0	(94)
#define AG_CG_BG_1_1	(95)
#define AG_CG_BG_1_2	(96)
#define AG_CG_BG_1_3	(97)
#define AG_CG_BG_1_4	(98)
#define AG_CG_BG_2_0	(99)
#define AG_CG_BG_2_1	(100)
#define AG_CG_BG_2_2	(101)
#define AG_CG_BG_2_3	(102)
#define AG_CG_BG_2_4	(103)
#define AG_CG_BG_3_0	(104)
#define AG_CG_BG_3_1	(105)
#define AG_CG_BG_3_2	(106)
#define AG_CG_BG_3_3	(107)
#define AG_CG_BG_3_4	(108)
#define AG_CG_BG_4_0	(109)
#define AG_CG_BG_4_1	(110)
#define AG_CG_BG_4_2	(111)
#define AG_CG_BG_4_3	(112)
#define AG_CG_BG_4_4	(113)
#define AG_CG_BG_0_0_0	(114)
#define AG_CG_BG_0_1_0	(115)
#define AG_CG_BG_0_0_1	(116)
#define AG_CG_BG_0_0_2	(117)
#define AG_CG_BG_0_0_3	(118)
#define AG_CG_BG_0_1_1	(119)
#define AG_CG_BG_0_1_2	(120)
#define AG_CG_BG_0_1_3	(121)
#define AG_CG_BG_0_2_0	(122)
#define AG_CG_BG_0_2_1	(123)
#define AG_CG_BG_0_2_2	(124)
#define AG_CG_BG_0_2_3	(125)
#define AG_CG_BG_0_3_0	(126)
#define AG_CG_BG_0_3_1	(127)
#define AG_CG_BG_0_3_2	(128)
#define AG_CG_BG_0_3_3	(129)
#define AG_CG_OBJ_TOGE	(130)
#define AG_CG_OBJ_TOGE_D	(131)
#define AG_CG_OBJ_TOGE_L	(132)
#define AG_CG_OBJ_TOGE_R	(133)
#define AG_CG_OBJ_TOGE4	(134)
#define AG_CG_OBJ_TOGE4_D	(135)
#define AG_CG_OBJ_TOGE4_L	(136)
#define AG_CG_OBJ_TOGE4_R	(137)
#define AG_CG_OBJ_CANNON	(138)
#define AG_CG_OBJ_BLOCK	(139)
#define AG_CG_OBJ_BLOCK_H	(140)
#define AG_CG_OBJ_BLOCK4_0	(141)
#define AG_CG_OBJ_BLOCK_H4	(142)
#define AG_CG_OBJ_LIFT	(143)
#define AG_CG_STORY_DAIGOROU	(144)
#define AG_CG_STORY_ERITAN	(145)
#define AG_CG_STORY_CLOUD_ERITAN	(146)
#define AG_CG_ITEM_MERONPAN256	(147)
#define AG_CG_ITEM_UNIXSP256	(148)
#define AG_CG_STORY_SHUCHU	(149)
#define AG_CG_STORY_SHUCHU_SUB	(150)
#define AG_CG_ITEM_MERONPAN64	(151)
#define AG_CG_ITEM_UNIXSP64	(152)
#define AG_CG_ITEM_ERITAN	(153)
#define AG_CG_ITEM_BONE_AG	(154)
#define AG_CG_ITEM_BONE_AU	(155)
#define AG_CG_ICON_DAIGORO	(156)
#define AG_CG_ICON_CROSS	(157)
#define AG_CG_ICON_STAR	(158)
#define AG_CG_TEXT_HIGHSCORE	(159)
#define AG_CG_TEXT_NEWRECORD	(160)
#define AG_CG_TEXT_SCORE	(161)

/***************************************************************/
/*                     RM3 Member Symbol                       */
/***************************************************************/
#define AG_RP_DAIGOROU_CLEAR	(0)
#define AG_RP_DAIGOROU_LOSE	(1)
#define AG_RP_DAIGOROU_ONIGIRI	(2)
#define AG_RP_DAIGOROU_GAMEOVER	(3)
#define AG_RP_DAIGOROU_JUMP	(4)
#define AG_RP_DAIGOROU_JUMPEND	(5)
#define AG_RP_DAIGOROU_JUMPSTART	(6)
#define AG_RP_DAIGOROU_RT	(7)
#define AG_RP_DAIGOROU_RUN	(8)
#define AG_RP_DAIGOROU_RUNEND	(9)
#define AG_RP_DAIGOROU_RUNSTART	(10)
#define AG_RP_DAIGOROU_WAIT	(11)
#define AG_RP_DAIGOROU_WALK	(12)
#define AG_RP_DAIGOROU_WALKEND	(13)
#define AG_RP_DAIGOROU_WALKSTART	(14)
#define AG_RP_EFF_RT	(15)
#define AG_RP_OBJ_EBULLET	(16)
#define AG_RP_OBJ_PBULLET	(17)
#define AG_RP_SIN_MESSAGE	(18)

/***************************************************************/
/*                       Vram Group Symbol                     */
/***************************************************************/

/***************************************************************/
/*                       Sound Member Symbol                   */
/***************************************************************/
#define AS_SND_BGM_2_441	(0)
#define AS_SND_BGM_2_441_HU	(1)
#define AS_SND_TITLE_1	(2)
#define AS_SND_GAMEOVER	(3)
#define AS_SND_GAMECLEAR	(4)
#define AS_SND_JUMP	(5)
#define AS_SND_TIMECOUNT	(6)
#define AS_SND_ATTACK1	(7)
#define AS_SND_ATTACK2	(8)
#define AS_SND_ATTACK3	(9)
#define AS_SND_GET1	(10)
#define AS_SND_GET2	(11)
#define AS_SND_GET3	(12)
#define AS_SND_CUT	(13)
#define AS_SND_LANDING	(14)
#define AS_SND_WALK_RIGHT	(15)
#define AS_SND_WALK_LEFT	(16)
#define AS_SND_DECIDE008	(17)
#define AS_SND_CANNON	(18)
#define AS_SND_CROW	(19)
#define AS_SND_FROG	(20)
#define AS_SND_A01	(21)
#define AS_SND_A02	(22)
#define AS_SND_A03	(23)
#define AS_SND_A04	(24)
#define AS_SND_B01	(25)
#define AS_SND_B02	(26)
#define AS_SND_B03	(27)
#define AS_SND_B04	(28)
#define AS_SND_B05	(29)
#define AS_SND_B06	(30)
#define AS_SND_B07	(31)
#define AS_SND_B08	(32)
#define AS_SND_B09	(33)
#define AS_SND_B10	(34)
#define AS_SND_B11	(35)

/***************************************************************/
/*                          Data Member                        */
/***************************************************************/
extern const AGERomMember ageRM[162];
extern const AGERM3Member ageRM3[19];
extern const u32 ageReserve[1];
extern const u32 ageUser[1];
extern const s16 ageVGCnt;
extern const AGESoundRomMember ageSRM[36];

#ifdef __cplusplus
}
#endif

#endif /* __AG_EXPORT__ */
