###########################################################################
#
#   Makefile for komachi
#
###########################################################################

#現在のディレクトリからランタイムルートディレクトリへの相対パス
ROOTDIR = ../../..

# CGROM ディレクトリ
CGROMDIR = .

# モジュール群
C_SRC  = main.c pad.c task.c mode.c work.c export.c randmt.c global.c \
	t_player.c t_bg.c t_static.c t_food.c t_key.c t_senario1.c t_opening.c t_score.c \
	t_frog.c t_object.c rect.c t_attack.c t_snake.c t_pbullet.c

include $(ROOTDIR)/include/makefile.def

## Makefile ends here.
